language: python

matrix:
  include:
    - os: linux
      python: "2.7"
    - os: osx
      python: "2.7"
      language: generic

before_install:
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update; fi
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install python; fi
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install gnu-tar; fi
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then virtualenv venv -p python; fi
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then source venv/bin/activate; fi

install: pip install -q -r requirements.txt -r requirements-tests.txt

script: ./test.sh
