language: python

matrix:
  include:
    - os: linux
      python: "2.7"
    - os: osx
      python: "2.7"
      language: generic

install: pip install -q -r requirements.txt -r requirements-tests.txt

script: ./test.sh
